blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/MohmmedAshraf/laravel-translations
    about: Read the Laravel Translations UI Pro documentation
  - name: ðŸ’¬ Discussions
    url: https://github.com/MohmmedAshraf/laravel-translations-pro-issues/discussions
    about: Ask questions and discuss ideas with the community
